
export const googleAPIKey = 'AIzaSyCR - PVpXe3PREHW8lysoPWtGp - DbjrFC7k';

export const fourSquareClientId = '20SGZBSFIJ2PAEM2E53DTZNVFZ5K1E4GHCNBKTXM14JVDKBD';

export const fourSquareClientSecret = 'C10LMFZC53BRQNH3CJ50SBWJLVWIPTQI4WYPKMPGYE0KZAXB';